title: Minimal theme
logo: /assets/img/logo.png
description: 
<p align="center">
<a href="https://sg.linkedin.com/in/sanjay-singh-0759214">LinkedIn</a> |
<a href="https://github.com/sanngh">GitHub</a> |
<a href=https://www.kaggle.com/sanngh>Kaggle</a>
<br>
I'm working on Data Science, Big Data, Spark, Meaching Learning related projects. 
Worked with Infosys, Head Strong and Birlasoft previously as Java Developer
I have worked in Credit Suisse AG since 2013 as a Solution Architect.
Since 2021 I have started working on ML space in Credit Suisse AG.
</br>
</p>
theme: jekyll-theme-minimal
