title: Minimal theme
logo: /assets/img/logo.png
description: 
<a href="https://sg.linkedin.com/in/sanjay-singh-0759214">LinkedIn</a>
<a href="https://github.com/sanngh">GitHub</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
